/// A comprehensive, strictly deduplicated set of ~1,000 high-frequency English
/// words representing CEFR A1-A2 vocabulary and core everyday lemmas.
///
/// Used as an offline baseline for "Band A: Basic / High-Frequency Vocabulary."
const Set<String> kCommonWordBank = {
  // A
  'a', 'ability', 'able', 'about', 'above', 'abroad', 'absence', 'absolute',
  'absolutely', 'academic', 'accept', 'acceptable', 'accepted', 'access',
  'accident', 'accidentally', 'accompany', 'according', 'account', 'accurate',
  'accurately', 'achieve', 'achieved', 'achievement', 'across', 'act', 'acted',
  'action', 'active', 'actively', 'activity', 'actor', 'actress', 'actual',
  'actually', 'ad', 'adapt', 'add', 'added', 'addition', 'additional',
  'address', 'adequate', 'adjust', 'administration', 'admit', 'admitted',
  'adopt', 'adult', 'advance', 'advanced', 'advantage', 'adventure',
  'advertise', 'advertisement', 'advertising', 'advice', 'advise', 'affair',
  'affect', 'affected', 'afford', 'afraid', 'after', 'afternoon', 'afterward',
  'afterwards', 'again', 'against', 'age', 'agency', 'agent', 'aggressive',
  'ago', 'agree', 'agreed', 'agreement', 'agriculture', 'ahead', 'aid', 'aim',
  'air', 'aircraft', 'airline', 'airport', 'alarm', 'album', 'alcohol',
  'alive', 'all', 'allow', 'allowed', 'almost', 'alone', 'along', 'already',
  'alright', 'also', 'alter', 'alternative', 'although', 'altogether',
  'always', 'am', 'amazing', 'ambition', 'ambulance', 'among', 'amount',
  'analyse', 'analysis', 'ancient', 'and', 'anger', 'angle', 'angry', 'animal',
  'ankle', 'anniversary', 'announce', 'announcement', 'annoy', 'annual',
  'another', 'answer', 'answered', 'anxious', 'any', 'anybody', 'anymore',
  'anyone', 'anything', 'anyway', 'anywhere', 'apart', 'apartment',
  'apologize', 'apology', 'apparent', 'apparently', 'appeal', 'appear',
  'appearance', 'appeared', 'apple', 'application', 'apply', 'applied',
  'appoint', 'appointment', 'appreciate', 'approach', 'appropriate',
  'approval', 'approve', 'approximate', 'approximately', 'april', 'architect',
  'architecture', 'area', 'are', 'argue', 'argued', 'argument', 'arise',
  'arm', 'armed', 'army', 'around', 'arrange', 'arrangement', 'arrest',
  'arrival', 'arrive', 'arrived', 'art', 'article', 'artificial', 'artist',
  'artistic', 'as', 'ashamed', 'aside', 'ask', 'asked', 'asleep', 'aspect',
  'assess', 'assessment', 'assignment', 'assist', 'assistance', 'assistant',
  'associate', 'association', 'assume', 'assumption', 'assure', 'at', 'ate',
  'atmosphere', 'attach', 'attack', 'attempt', 'attend', 'attention',
  'attitude', 'attorney', 'attract', 'attraction', 'attractive', 'audience',
  'august', 'aunt', 'author', 'authority', 'autumn', 'available', 'average',
  'avoid', 'avoided', 'awake', 'award', 'aware', 'awareness', 'away', 'awful',

  // B
  'baby', 'back', 'bad', 'badly', 'bag', 'bake', 'balance', 'ball', 'band',
  'bank', 'bar', 'barely', 'base', 'based', 'basic', 'basically', 'basis',
  'bath', 'bathroom', 'be', 'beach', 'bear', 'beat', 'beautiful', 'beauty',
  'became', 'because', 'become', 'bed', 'bedroom', 'been', 'beer', 'before',
  'began', 'begin', 'beginning', 'begun', 'behalf', 'behave', 'behavior',
  'behind', 'being', 'belief', 'believe', 'believed', 'belong', 'belonged',
  'below', 'beneath', 'benefit', 'beside', 'besides', 'best', 'better',
  'between', 'beyond', 'big', 'bill', 'billion', 'bird', 'birth', 'birthday',
  'bit', 'bite', 'bitter', 'black', 'blame', 'blind', 'block', 'blood',
  'blow', 'blue', 'board', 'boat', 'body', 'boil', 'bomb', 'bone', 'book',
  'border', 'bored', 'boring', 'born', 'borrow', 'boss', 'both', 'bottle',
  'bottom', 'bought', 'bound', 'box', 'boy', 'brain', 'branch', 'brave',
  'bread', 'break', 'breakfast', 'breath', 'breathe', 'bridge', 'brief',
  'bright', 'brilliant', 'bring', 'broad', 'broke', 'broken', 'brother',
  'brought', 'brown', 'brush', 'build', 'building', 'built', 'burn', 'burned',
  'burnt', 'bus', 'business', 'busy', 'but', 'butter', 'button', 'buy',
  'buying', 'by',

  // C
  'cabinet', 'cable', 'cafe', 'cake', 'calculate', 'calendar', 'call', 'called',
  'calm', 'camera', 'camp', 'campaign', 'can', 'cancer', 'candidate', 'cap',
  'capable', 'capacity', 'capital', 'captain', 'capture', 'car', 'card',
  'care', 'cared', 'career', 'careful', 'carefully', 'careless', 'carpet',
  'carry', 'carried', 'case', 'cash', 'cast', 'castle', 'cat', 'catch',
  'caught', 'cause', 'caused', 'celebrate', 'celebration', 'cell', 'center',
  'central', 'centre', 'century', 'certain', 'certainly', 'chain', 'chair',
  'chairman', 'challenge', 'champion', 'chance', 'change', 'changed', 'channel',
  'chapter', 'character', 'characteristic', 'charge', 'charity', 'chart',
  'cheap', 'check', 'checked', 'cheek', 'cheese', 'chemical', 'chest',
  'chicken', 'chief', 'child', 'children', 'choice', 'choose', 'chose',
  'chosen', 'church', 'cinema', 'circle', 'circumstance', 'citizen', 'city',
  'civil', 'claim', 'class', 'classic', 'classroom', 'clean', 'cleaned',
  'clear', 'cleared', 'clearly', 'clerk', 'clever', 'client', 'climate',
  'climb', 'climbed', 'clock', 'close', 'closed', 'closely', 'closer',
  'clothes', 'clothing', 'cloud', 'club', 'clue', 'coach', 'coal', 'coast',
  'coat', 'code', 'coffee', 'cold', 'colleague', 'collect', 'collected',
  'collection', 'college', 'color', 'column', 'combination', 'combine',
  'come', 'comedy', 'comfort', 'comfortable', 'coming', 'command', 'comment',
  'commercial', 'commission', 'commit', 'committee', 'common',
  'communication', 'community', 'company', 'compare', 'compared', 'comparison',
  'compete', 'competition', 'competitive', 'complain', 'complaint', 'complete',
  'completed', 'completely', 'complex', 'complicated', 'component', 'computer',
  'concentrate', 'concept', 'concern', 'concerned', 'concert', 'conclude',
  'conclusion', 'condition', 'conduct', 'conference', 'confidence', 'confident',
  'confirm', 'conflict', 'confuse', 'confused', 'connect', 'connection',
  'conscious', 'consequence', 'consider', 'considerable', 'consideration',
  'considered', 'consist', 'constant', 'constantly', 'construct',
  'construction', 'consult', 'consumer', 'contact', 'contain', 'contained',
  'content', 'contest', 'context', 'continue', 'continued', 'continuous',
  'contract', 'contrast', 'contribute', 'contribution', 'control', 'controlled',
  'convenient', 'conversation', 'convert', 'convince', 'cook', 'cooked',
  'cookie', 'cool', 'cooperation', 'cope', 'copy', 'copied', 'core', 'corner',
  'correct', 'correctly', 'cost', 'costs', 'cottage', 'cotton', 'couch',
  'could', 'council', 'count', 'counted', 'counter', 'country', 'countryside',
  'county', 'couple', 'courage', 'course', 'court', 'cousin', 'cover',
  'covered', 'cow', 'crack', 'craft', 'crash', 'crazy', 'cream', 'create',
  'created', 'creation', 'creative', 'creature', 'credit', 'crew', 'crime',
  'criminal', 'crisis', 'criteria', 'critical', 'criticism', 'criticize',
  'crop', 'cross', 'crossed', 'crowd', 'crowded', 'crucial', 'cruel', 'crush',
  'cry', 'cried', 'cultural', 'culture', 'cup', 'cure', 'curious', 'current',
  'currently', 'curtain', 'curve', 'custom', 'customer', 'cut', 'cycle',

  // D
  'dad', 'daily', 'damage', 'damaged', 'dance', 'danced', 'danger', 'dangerous',
  'dare', 'dark', 'darkness', 'data', 'date', 'daughter', 'day', 'days',
  'dead', 'deal', 'dealt', 'dear', 'death', 'debate', 'debt', 'decade',
  'december', 'decent', 'decide', 'decided', 'decision', 'declare', 'decline',
  'deep', 'deeply', 'defeat', 'defence', 'defend', 'defense', 'definite',
  'definitely', 'definition', 'degree', 'delay', 'deliver', 'delivered',
  'delivery', 'demand', 'democracy', 'democratic', 'demonstrate',
  'demonstration', 'deny', 'department', 'depend', 'depended', 'dependent',
  'deposit', 'depression', 'depth', 'derive', 'describe', 'described',
  'description', 'desert', 'deserve', 'design', 'designed', 'desire', 'desk',
  'despair', 'desperate', 'despite', 'destroy', 'destroyed', 'destruction',
  'detail', 'detailed', 'determination', 'determine', 'determined', 'develop',
  'developed', 'development', 'device', 'devil', 'devote', 'dialogue', 'die',
  'died', 'diet', 'difference', 'different', 'difficult', 'difficulty', 'dig',
  'dinner', 'direct', 'direction', 'directly', 'director', 'dirt', 'dirty',
  'disabled', 'disagree', 'disappear', 'disappeared', 'disappoint',
  'disappointed', 'disappointment', 'disaster', 'discipline', 'discount',
  'discover', 'discovered', 'discovery', 'discuss', 'discussed', 'discussion',
  'disease', 'dish', 'dismiss', 'display', 'dispute', 'distance', 'distant',
  'distinct', 'distinction', 'distinguish', 'distribute', 'distribution',
  'district', 'disturb', 'divide', 'divided', 'division', 'divorce', 'do',
  'doctor', 'document', 'does', 'dog', 'doing', 'dollar', 'domestic',
  'dominant', 'dominate', 'done', 'door', 'double', 'doubt', 'doubtless',
  'down', 'downstairs', 'downtown', 'draft', 'drag', 'drama', 'dramatic',
  'drank', 'draw', 'drawing', 'drawn', 'dream', 'dress', 'dressed', 'drew',
  'drink', 'drive', 'driven', 'driver', 'drop', 'dropped', 'drove', 'drug',
  'drunk', 'dry', 'due', 'dull', 'during', 'dust', 'duty',

  // E
  'each', 'ear', 'early', 'earn', 'earth', 'ease', 'easily', 'east', 'eastern',
  'easy', 'eat', 'eaten', 'economic', 'economy', 'edge', 'edition', 'editor',
  'educate', 'education', 'educational', 'effect', 'effective', 'effectively',
  'efficiency', 'efficient', 'effort', 'egg', 'eight', 'eighteen', 'eighty',
  'either', 'elderly', 'elect', 'election', 'electric', 'electrical',
  'electricity', 'electronic', 'element', 'elementary', 'eleven', 'else',
  'elsewhere', 'email', 'embarrassed', 'emergency', 'emotion', 'emotional',
  'emphasis', 'emphasize', 'empire', 'employ', 'employee', 'employer',
  'employment', 'empty', 'enable', 'encounter', 'encourage', 'encouraged',
  'end', 'ended', 'enemy', 'energy', 'engage', 'engine', 'engineer',
  'engineering', 'english', 'enhance', 'enjoy', 'enjoyable', 'enjoyed',
  'enormous', 'enough', 'ensure', 'enter', 'entered', 'enterprise',
  'entertain', 'entertainment', 'enthusiasm', 'entire', 'entirely', 'entitle',
  'entrance', 'entry', 'envelope', 'environment', 'environmental', 'episode',
  'equal', 'equally', 'equipment', 'era', 'error', 'escape', 'escaped',
  'especially', 'essay', 'essential', 'establish', 'establishment', 'estate',
  'estimate', 'ethnic', 'european', 'evaluate', 'evaluation', 'even',
  'evening', 'event', 'eventually', 'ever', 'every', 'everybody', 'everyone',
  'everything', 'everywhere', 'evidence', 'evil', 'exact', 'exactly',
  'examine', 'examined', 'example', 'excellent', 'except', 'exception',
  'exchange', 'excited', 'excitement', 'exciting', 'exclude', 'excuse',
  'executive', 'exercise', 'exhibition', 'exist', 'existed', 'existence',
  'existing', 'exit', 'expand', 'expansion', 'expect', 'expectation',
  'expected', 'expense', 'expensive', 'experience', 'experienced',
  'experiment', 'expert', 'explain', 'explained', 'explanation', 'explode',
  'explore', 'explosion', 'export', 'expose', 'express', 'expressed',
  'expression', 'extend', 'extension', 'extensive', 'extent', 'external',
  'extra', 'extraordinary', 'extreme', 'extremely', 'eye',

  // F
  'face', 'facility', 'fact', 'factor', 'factory', 'faculty', 'fade', 'fail',
  'failed', 'failure', 'fair', 'fairly', 'faith', 'fall', 'fallen', 'false',
  'familiar', 'family', 'famous', 'fan', 'far', 'farm', 'farmer', 'farming',
  'fashion', 'fast', 'fat', 'father', 'fault', 'favor', 'favourite', 'fear',
  'feasible', 'feather', 'feature', 'february', 'fed', 'fee', 'feed', 'feel',
  'feeling', 'fellow', 'felt', 'female', 'fence', 'fever', 'few', 'fewer',
  'fewest', 'field', 'fifteen', 'fifth', 'fifty', 'fight', 'fighter',
  'fighting', 'figure', 'file', 'fill', 'filled', 'film', 'final', 'finally',
  'finance', 'financial', 'find', 'finding', 'fine', 'finger', 'finish',
  'finished', 'fire', 'firm', 'firmly', 'first', 'firstly', 'fish', 'fishing',
  'fit', 'fitted', 'five', 'fix', 'fixed', 'flag', 'flame', 'flash', 'flat',
  'flew', 'flight', 'floor', 'flour', 'flow', 'flower', 'flown', 'fly',
  'focus', 'fold', 'folk', 'follow', 'followed', 'following', 'food', 'foot',
  'football', 'for', 'force', 'foreign', 'forest', 'forever', 'forget',
  'forgive', 'forgot', 'forgotten', 'form', 'formal', 'formation', 'former',
  'formerly', 'forth', 'fortunate', 'fortunately', 'fortune', 'forty',
  'forward', 'foster', 'found', 'foundation', 'founder', 'four', 'fourteen',
  'fourth', 'frame', 'framework', 'frankly', 'free', 'freedom', 'freeze',
  'frequency', 'frequent', 'frequently', 'fresh', 'friday', 'fridge',
  'friend', 'friendly', 'friendship', 'frightened', 'from', 'front', 'frozen',
  'fruit', 'fuel', 'full', 'fully', 'fun', 'function', 'fund', 'fundamental',
  'funeral', 'funny', 'furniture', 'further', 'furthermore', 'future',

  // G
  'gain', 'gained', 'gallery', 'game', 'gang', 'gap', 'garage', 'garden',
  'gas', 'gate', 'gather', 'gave', 'gear', 'gender', 'gene', 'general',
  'generally', 'generate', 'generation', 'generous', 'genetic', 'gentle',
  'gentleman', 'gently', 'genuine', 'gesture', 'get', 'getting', 'ghost',
  'giant', 'gift', 'girl', 'girlfriend', 'give', 'given', 'giving', 'glad',
  'glance', 'glass', 'global', 'glove', 'go', 'goal', 'god', 'goes', 'going',
  'gold', 'golden', 'golf', 'gone', 'good', 'government', 'governor', 'grab',
  'grade', 'gradually', 'graduate', 'grain', 'grand', 'grandfather',
  'grandmother', 'grant', 'grass', 'grateful', 'great', 'greatly', 'green',
  'greet', 'grew', 'grey', 'ground', 'group', 'grow', 'growing', 'growth',
  'guarantee', 'guard', 'guess', 'guessed', 'guest', 'guidance', 'guide',
  'guideline', 'guilty', 'guitar', 'gun', 'guy', 'habit',

  // H
  'had', 'hair', 'half', 'hall', 'hand', 'handle', 'handled', 'hang',
  'happen', 'happened', 'happy', 'harbor', 'hard', 'hardly', 'harm', 'hat',
  'hate', 'hated', 'have', 'having', 'he', 'head', 'headline', 'headquarters',
  'heal', 'health', 'healthy', 'hear', 'heard', 'hearing', 'heart', 'heat',
  'heater', 'heaven', 'heavily', 'heavy', 'height', 'held', 'hell', 'hello',
  'help', 'helped', 'helpful', 'helpless', 'hence', 'her', 'here', 'hero',
  'hers', 'herself', 'hesitate', 'hide', 'hidden', 'high', 'highlight',
  'highly', 'highway', 'hill', 'him', 'himself', 'hire', 'his', 'historian',
  'historic', 'historical', 'history', 'hit', 'hobby', 'hold', 'holding',
  'hole', 'holiday', 'holy', 'home', 'homeless', 'honest', 'honestly',
  'honey', 'honor', 'hook', 'hope', 'hoped', 'hopeful', 'hopefully',
  'hopeless', 'horizon', 'horn', 'horrible', 'horror', 'horse', 'hospital',
  'host', 'hot', 'hotel', 'hour', 'hours', 'house', 'household', 'housing',
  'how', 'however', 'huge', 'human', 'humor', 'hundred', 'hungry', 'hunt',
  'hunter', 'hurry', 'hurt', 'husband',

  // I
  'i', 'ice', 'idea', 'ideal', 'identify', 'identified', 'identity', 'if',
  'ignore', 'ill', 'illegal', 'illness', 'illustrate', 'image', 'imagination',
  'imagine', 'imagined', 'immediate', 'immediately', 'immigrant', 'impact',
  'implement', 'implication', 'imply', 'import', 'importance', 'important',
  'impose', 'impossible', 'impress', 'impression', 'impressive', 'improve',
  'improved', 'improvement', 'in', 'incentive', 'incident', 'include',
  'included', 'including', 'income', 'incorporate', 'increase', 'increased',
  'increasingly', 'incredible', 'incredibly', 'indeed', 'independence',
  'independent', 'index', 'indicate', 'indication', 'indirect', 'individual',
  'industrial', 'industry', 'inevitable', 'infant', 'infection', 'inflation',
  'influence', 'inform', 'informal', 'information', 'informed', 'infrastructure',
  'ingredient', 'initial', 'initially', 'initiative', 'injure', 'injury',
  'inner', 'innocent', 'innovation', 'input', 'inquiry', 'inside', 'insight',
  'insist', 'inspire', 'install', 'instance', 'instant', 'instantly',
  'instead', 'institute', 'institution', 'instruction', 'instructor',
  'instrument', 'insurance', 'intellectual', 'intelligence', 'intelligent',
  'intend', 'intended', 'intense', 'intention', 'interaction', 'interest',
  'interested', 'interesting', 'internal', 'international', 'internet',
  'interpret', 'interpretation', 'interrupt', 'interval', 'intervention',
  'interview', 'into', 'introduce', 'introduced', 'introduction', 'invent',
  'invention', 'invest', 'investigate', 'investigation', 'investment',
  'investor', 'invite', 'invited', 'involve', 'involved', 'involvement',
  'iron', 'island', 'issue', 'it', 'item', 'its', 'itself',

  // J
  'jacket', 'jail', 'january', 'jealous', 'jeans', 'jet', 'jewellery', 'job',
  'join', 'joined', 'joint', 'joke', 'journal', 'journalist', 'journey',
  'joy', 'judge', 'judgment', 'juice', 'july', 'jump', 'jumped', 'june',
  'junior', 'jury', 'just', 'justice', 'justify',

  // K
  'keen', 'keep', 'keeping', 'kept', 'key', 'kick', 'kicked', 'kid', 'kids',
  'kill', 'killed', 'killer', 'killing', 'kind', 'kindly', 'king', 'kiss',
  'kitchen', 'knee', 'knife', 'knock', 'know', 'knowing', 'knowledge',
  'known', 'knew',

  // L
  'label', 'laboratory', 'labour', 'lack', 'lady', 'lake', 'land', 'landscape',
  'lane', 'language', 'large', 'largely', 'last', 'late', 'lately', 'later',
  'latest', 'latter', 'laugh', 'laughed', 'launch', 'laundry', 'law', 'lawn',
  'lawyer', 'lay', 'layer', 'lazy', 'lead', 'leader', 'leadership', 'leading',
  'leaf', 'league', 'lean', 'learn', 'learned', 'learnt', 'learning', 'least',
  'leather', 'leave', 'leaving', 'lecture', 'led', 'left', 'leg', 'legal',
  'legend', 'legislation', 'legitimate', 'leisure', 'lend', 'lent', 'length',
  'less', 'lesson', 'let', 'letter', 'level', 'liberal', 'library', 'licence',
  'lie', 'life', 'lifestyle', 'lifetime', 'lift', 'lifted', 'light', 'lighting',
  'like', 'liked', 'likely', 'limit', 'limitation', 'limited', 'line', 'link',
  'lip', 'liquid', 'list', 'listen', 'listened', 'listener', 'literally',
  'literary', 'literature', 'little', 'live', 'lived', 'lively', 'living',
  'load', 'loan', 'local', 'locate', 'location', 'lock', 'logic', 'logical',
  'lonely', 'long', 'look', 'looked', 'looking', 'loose', 'lose', 'losing',
  'loss', 'lost', 'lot', 'lots', 'loud', 'loudly', 'love', 'loved', 'lovely',
  'lover', 'low', 'lower', 'loyal', 'loyalty', 'luck', 'lucky', 'lunch',
  'lung', 'luxury',

  // M
  'machine', 'machinery', 'mad', 'magazine', 'magic', 'mail', 'main', 'mainly',
  'maintain', 'maintenance', 'major', 'majority', 'make', 'making', 'male',
  'mall', 'man', 'manage', 'managed', 'management', 'manager', 'manner',
  'manufacturer', 'manufacturing', 'many', 'map', 'march', 'margin', 'mark',
  'marked', 'market', 'marketing', 'marriage', 'married', 'marry', 'marvelous',
  'mass', 'massive', 'master', 'match', 'matched', 'material', 'math',
  'matter', 'mattered', 'maximum', 'may', 'maybe', 'mayor', 'me', 'meal',
  'mean', 'meaning', 'meaningful', 'means', 'meant', 'meanwhile', 'measure',
  'measured', 'measurement', 'meat', 'mechanism', 'media', 'medical',
  'medication', 'medicine', 'medium', 'meet', 'meeting', 'member',
  'membership', 'memory', 'men', 'mental', 'mention', 'mentioned', 'menu',
  'mere', 'merely', 'message', 'metal', 'method', 'middle', 'midnight',
  'might', 'military', 'milk', 'million', 'mind', 'minded', 'mine', 'mineral',
  'minimum', 'minister', 'ministry', 'minor', 'minority', 'minute', 'minutes',
  'mirror', 'miss', 'missed', 'missile', 'missing', 'mission', 'mistake',
  'mix', 'mixed', 'mixture', 'mobile', 'mode', 'model', 'moderate', 'modern',
  'modest', 'mom', 'moment', 'monday', 'money', 'monitor', 'month', 'months',
  'mood', 'moon', 'moral', 'more', 'moreover', 'morning', 'mortgage', 'most',
  'mostly', 'mother', 'motion', 'motivation', 'motor', 'mount', 'mountain',
  'mouse', 'mouth', 'move', 'moved', 'movement', 'movie', 'moving', 'much',
  'multiple', 'murder', 'muscle', 'museum', 'music', 'musical', 'musician',
  'must', 'my', 'myself', 'mystery',

  // N
  'nail', 'name', 'named', 'narrative', 'narrow', 'nation', 'national',
  'native', 'natural', 'naturally', 'nature', 'near', 'nearby', 'nearly',
  'neat', 'necessarily', 'necessary', 'necessity', 'neck', 'need', 'needed',
  'negative', 'negotiate', 'negotiation', 'neighbor', 'neighbour',
  'neighborhood', 'neither', 'nerve', 'nervous', 'net', 'network', 'never',
  'nevertheless', 'new', 'newly', 'news', 'newspaper', 'next', 'nice',
  'nicely', 'night', 'nightly', 'nights', 'nine', 'nineteen', 'ninety', 'no',
  'nobody', 'nod', 'noise', 'noisy', 'nomination', 'none', 'nonetheless',
  'nonsense', 'noon', 'nor', 'normal', 'normally', 'north', 'northern',
  'nose', 'not', 'notably', 'note', 'noted', 'nothing', 'notice', 'noticed',
  'notion', 'novel', 'november', 'now', 'nowadays', 'nowhere', 'nuclear',
  'number', 'numerous', 'nurse', 'nut',

  // O
  'object', 'objective', 'obligation', 'observation', 'observe', 'obtain',
  'obtained', 'obvious', 'obviously', 'occasion', 'occasional', 'occasionally',
  'occupation', 'occupy', 'occur', 'occurred', 'ocean', 'october', 'odd',
  'odds', 'of', 'off', 'offence', 'offend', 'offensive', 'offer', 'offered',
  'office', 'officer', 'official', 'officially', 'often', 'oil', 'ok', 'okay',
  'old', 'on', 'once', 'one', 'ones', 'ongoing', 'online', 'only', 'onto',
  'open', 'opened', 'opening', 'openly', 'operate', 'operating', 'operation',
  'operator', 'opinion', 'opponent', 'opportunity', 'oppose', 'opposite',
  'opposition', 'option', 'or', 'orange', 'order', 'ordered', 'ordinary',
  'organ', 'organic', 'organization', 'organize', 'organized', 'origin',
  'original', 'originally', 'other', 'others', 'otherwise', 'ought', 'our',
  'ours', 'ourselves', 'out', 'outcome', 'outdoor', 'outlet', 'outline',
  'output', 'outside', 'outstanding', 'oven', 'over', 'overall', 'overcome',
  'overlook', 'owe', 'own', 'owned', 'owner', 'ownership',

  // P
  'pack', 'package', 'page', 'pain', 'painful', 'paint', 'painter', 'painting',
  'pair', 'pale', 'palm', 'pan', 'panel', 'panic', 'pant', 'pants', 'paper',
  'parent', 'parents', 'park', 'parking', 'part', 'partial', 'partially',
  'participant', 'participate', 'participation', 'particular', 'particularly',
  'partly', 'partner', 'partnership', 'party', 'pass', 'passage', 'passed',
  'passenger', 'passion', 'past', 'path', 'patience', 'patient', 'pattern',
  'pause', 'pay', 'paying', 'payment', 'peace', 'peaceful', 'peak', 'pen',
  'penalty', 'pencil', 'pension', 'people', 'pepper', 'per', 'perceive',
  'percentage', 'perception', 'perfect', 'perfectly', 'perform', 'performance',
  'performed', 'perhaps', 'period', 'permanent', 'permission', 'permit',
  'person', 'personal', 'personality', 'personally', 'personnel', 'perspective',
  'persuade', 'pet', 'phase', 'phenomenon', 'philosophy', 'phone', 'photo'
};